
name: Catkin CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [ubuntu-18.04]

    strategy:
      matrix:
        compiler: ["/usr/bin/g++", "/usr/bin/clang++"]

    steps:
    - uses: actions/checkout@v2
    - uses: janbernloehr/github-setup-catkin@master
      with:
        ros-version: 'melodic'
        workspace: '$GITHUB_WORKSPACE'
    - run: catkin build -sc -DCMAKE_C_COMPILER=${{ matrix.compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
